spring:
  datasource:
    url: jdbc:mysql://mysql:3306/payment?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: payment
    password: payment

  jpa:
    hibernate:
      ddl-auto: update